### ISSUE TITLE
Confirmation Dialog is broken - at least for NB 12.2 / JDK 15 on Windows 10

### ISSUE THREAD

**Issue by gtsh** [junichi11/netbeans-change-lf#24]
After toggeling 'Show confirmation dialog before adjusting the line endings' in the configuration, the dialog indeed showed up, - but was devoid of any controls, not even allowing to be closed by clicking into the x or using ALT-F4. Since it is also modal, this left no other option as to kill Netbeans using the taskmanager, and deselecting the option.

**Comment by gtsh** [comment]
Found a way to fix it, but still, this is weird:
As it turns out, this somehow hinges on using jaxb-api-2.2.3.jar and jaxb-impl-2.3.0.1.jar. But early in the NB startup; you see something like this:

Boot & Ext. Classpath   = 
  Application Classpath   = C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\lib\boot.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\lib\org-openide-modules.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\lib\org-openide-util-lookup.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\lib\org-openide-util-ui.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\lib\org-openide-util.jar
  Startup Classpath       = C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\core\asm-8.0.1.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\core\asm-commons-8.0.1.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\core\asm-tree-8.0.1.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\core\core-base.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\core\core.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\core\org-netbeans-libs-asm.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\core\org-openide-filesystems-compat8.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\platform\core\org-openide-filesystems.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\nb\core\org-netbeans-upgrader.jar;C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\nb\core\locale\core_nb.jar
     -------------------------------------------------------------------------------
WARNING [org.netbeans.core.startup.NbEvents]: The extension C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\ide\modules\ext\jcodings-1.0.18.jar may be multiply loaded by modules: [C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\ide\modules\org-netbeans-modules-textmate-lexer.jar, C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\ide\modules\org-netbeans-libs-bytelist.jar]; see: http://www.netbeans.org/download/dev/javadoc/org-openide-modules/org/openide/modules/doc-files/classpath.html#class-path
WARNING [org.netbeans.core.modules]: had to upgrade dependencies for module com.codename1: added = [module org.netbeans.modules.project.ant.ui/1 > 1.62, module org.netbeans.api.templates > 1.0, module org.openide.execution.compat8 > 9.0, module org.netbeans.modules.projectuiapi.base/1 > 1.78.0, module org.openide.util.ui > 9.3, module org.openide.filesystems.nb, module org.openide.filesystems.compat8, module org.netbeans.modules.editor.document > 1.0, module org.netbeans.modules.project.ant.compat8/1 > 1.62] removed = []; details: [#243100: Separate desktop-independent utilities, Removal of FileSystemCapability, Separate project.ant into desktop and NetBeans independent and dependent parts, Separate projectuiapi into desktop and NetBeans independent and dependent parts, Separation of Parsing and Indexing APIs, Separation of desktop and cleanup, Templates API has been separated into its own module.]
WARNING [org.netbeans.core.modules]: had to upgrade dependencies for module org.netbeans.module.confirmexit: added = [module org.openide.util.ui > 9.3] removed = []; details: [#243100: Separate desktop-independent utilities]
WARNING [org.netbeans.core.modules]: had to upgrade dependencies for module org.netbeans.modules.h2: added = [module org.openide.awt, module org.openide.util.lookup, module org.openide.util.lookup > 8.0, module org.openide.util.ui > 9.3, module org.openide.filesystems.nb, module org.openide.execution.compat8 > 9.0, module org.openide.filesystems.compat8] removed = []; details: [#170056: Separate module for Lookup API, #243100: Separate desktop-independent utilities, FileObject implements Lookup.Provider, Removal of FileSystemCapability, SaveCookie extends Savable. To compile you need to include openide.awt on classpath., Separation of desktop and cleanup]
WARNING [org.netbeans.JarClassLoader]: Opening C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\java\maven\lib\cdi-api-1.0.jar took 511 ms
INFO [com.raelity.logman.netbeans.Installer]: doInit: initialization: ModuleInstall: validate
INFO [org.netbeans.JarClassLoader]: C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\extra\modules\ext\jaxb-api-2.2.3.jar does not exist, # of retries 0
INFO [org.netbeans.JarClassLoader]: file C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\extra\modules\ext exists. # of retries 0
INFO [org.netbeans.JarClassLoader]: C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\extra\modules\ext is directory and contains: [ClientWizard_stubs.jar, com.github.alexfalappa.nb-springboot-plugin, com.junichi11.netbeans.github.issues, com.raelity.logman.netbeans, controlsfx-8.40.12.jar, freemarker-2.3.23.jar, gson-2.2.4-for-vagrant.jar, ide-plugin-templates-2.10.2.jar, javafx-base-13-win.jar, javafx-controls-13-win.jar, javafx-graphics-13-win.jar, javafx-media-13-win.jar, javafx-swing-13-win.jar, javafx-web-13-win.jar, JavaSE.jar, javax.json-1.0.4.jar, jsoup-1.7.2-for-nb-vagrant-plugin.jar, jsoup-License, log4j-1.2-api-2.5.jar, log4j-api-2.5.jar, log4j-core-2.5.jar, org.bitbucket.draganbjedov.netbeans-csv-editor]
**INFO [org.netbeans.JarClassLoader]: Cannot open C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\extra\modules\ext\jaxb-api-2.2.3.jar
java.nio.file.NoSuchFileException: C:\Users\--- some hiden user ---\tool\apache.org\netbeans\12.2\extra\modules\ext\jaxb-api-2.2.3.jar**
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)

... indicating that the jar isn't there! 
Fixing this, by actually placing it there, and afterwards, doing the same with the also missing impl, actually fixes the problem with the dialog too.

So it seems, there is actually something broken with the installation.
To be frank, I noticed problems with those two jars already in all versions starting from NB 9, breaking the installation of various plugins. So this might be a generall problem.

**Comment by gtsh** [comment]
Also note, that NB actually has jaxb-api.jar and jaxb-impl.jar, but residing in ide/module/ext/jaxb/... and of a more recent version. For me, using mklink to create hard links to those from extra\modules\ext did the trick without adding additional jars.

Don't now whether this will wreck havoc elsewhere though...

**Comment by junichi11** [comment]
I'll have a look at it later. Thanks for reporting it.

**Comment by junichi11** [comment]
Could you please try to use the dev version(0.9.0.1-dev)? : https://github.com/junichi11/netbeans-change-lf/releases/tag/v0.9.0

**Comment by junichi11** [comment]
> Fixing this, by actually placing it there, and afterwards, doing the same with the also missing impl, actually fixes the problem with the dialog too.
> 
> So it seems, there is actually something broken with the installation.
> To be frank, I noticed problems with those two jars already in all versions starting from NB 9, breaking the installation of various plugins. So this might be a generall problem.

@gtsh 
If it's an IDE problem, please report it to the [JIRA](https://issues.apache.org/jira/projects/NETBEANS/issues) :) Thanks.

**Comment by faraz-wq** [comment]
> Also note, that NB actually has jaxb-api.jar and jaxb-impl.jar, but residing in ide/module/ext/jaxb/... and of a more recent version. For me, using mklink to create hard links to those from extra\modules\ext did the trick without adding additional jars.
> 
> Don't now whether this will wreck havoc elsewhere though...

Can you give the exact locations where I need to paste both the jars
